# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: prometheus
#   namespace: argocd
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   destination:
#     namespace: monitoring
#     server: https://kubernetes.default.svc
#   project: default
#   source:
#     path: helm/kube-prometheus-stack-custom
#     repoURL: https://github.com/SergeyDz/argocd-education
#     targetRevision: HEAD
#     helm:
#       valueFiles:
#       - values.yaml
#   syncPolicy:
#     automated: 
#       prune: true
#       selfHeal: true
#     syncOptions: 
#       - CreateNamespace=true